
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import Navbar from '@/components/Navbar';
import FileUpload from '@/components/FileUpload';
import YouTubeSummarizer from '@/components/YouTubeSummarizer';
import SummaryViewer from '@/components/SummaryViewer';
import SolutionGenerator from '@/components/SolutionGenerator';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { 
  FileText, Youtube, Lightbulb, CircleHelp, BookText, BookOpen, Calendar,
  BarChart, Brain, Check, CheckCircle, Clock, Search, Star, Zap, AlertCircle,
  PenTool, GraduationCap, ChevronRight, ArrowRight, Sparkles, MessageCircle
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';

const Dashboard = () => {
  const [documentSummary, setDocumentSummary] = useState(null);
  const [videoSummary, setVideoSummary] = useState(null);
  const [activeTab, setActiveTab] = useState("documents");
  const [searchQuery, setSearchQuery] = useState("");

  // Mock data for summaries
  const recentSummaries = [
    {
      title: "Introduction to Organic Chemistry",
      summary: "This document covers the fundamentals of organic chemistry, including basic principles of carbon compounds, functional groups, and chemical bonding in organic molecules.",
      date: "2 days ago",
      type: "document",
      progress: 95
    },
    {
      title: "Machine Learning Basics: Neural Networks",
      summary: "An overview of neural network architecture, backpropagation, activation functions, and common use cases in modern applications.",
      date: "3 days ago",
      type: "document",
      progress: 78
    },
    {
      title: "Quantum Physics Explained",
      summary: "Video explaining the core concepts of quantum mechanics including wave-particle duality, uncertainty principle, and quantum entanglement.",
      date: "1 week ago",
      type: "video",
      progress: 62
    }
  ];

  const handleFileUpload = (file) => {
    console.log("File uploaded:", file);
    
    // Simulate processing the file and getting a summary
    setTimeout(() => {
      const mockSummary = {
        title: file.name.replace(/\.[^/.]+$/, ""), // Remove file extension
        summary: "This is a simulated summary of the uploaded document. In a real application, this would be generated by AI based on the actual document content. The summary would provide a concise overview of the main topics and concepts covered in the material.",
        keyPoints: [
          "First key point extracted from the document",
          "Second important concept from the study material",
          "Third significant idea or definition",
          "Fourth notable fact or theory",
          "Fifth critical element from the document"
        ]
      };
      
      setDocumentSummary(mockSummary);
      toast({
        title: "Summary Generated",
        description: `Successfully analyzed "${file.name}" and generated a summary.`,
      });
    }, 500);
  };

  const handleVideoSummarize = (summary) => {
    console.log("Video summarized:", summary);
    setVideoSummary(summary);
    toast({
      title: "Video Summarized",
      description: "Successfully extracted key points from the video.",
    });
  };

  const fadeInUp = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } }
  };

  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { 
      opacity: 1, 
      y: 0, 
      transition: { 
        duration: 0.4,
      } 
    },
    hover: {
      y: -5,
      boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.05)",
      transition: { duration: 0.2 }
    }
  };

  return (
    <div className="min-h-screen bg-background transition-colors duration-300">
      <Navbar />
      
      <main className="app-container py-10">
        <motion.div
          initial="hidden"
          animate="visible"
          variants={fadeInUp}
          className="mb-10"
        >
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8">
            <div>
              <h1 className="text-3xl font-bold mb-2 bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent animate-gradient">Your Study Dashboard</h1>
              <p className="text-muted-foreground">Access all your study tools and materials in one place</p>
            </div>
            <div className="mt-4 md:mt-0 relative w-full max-w-xs">
              <Input 
                className="pl-10 bg-background/80 backdrop-blur-sm border-border/40 focus:border-primary/40"
                placeholder="Search summaries, notes..." 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
              <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
            </div>
          </div>
        
          {/* Quick stats with enhanced styling */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1, duration: 0.4 }}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              className="glass-card p-4 rounded-xl border border-border/40 flex items-center space-x-4 hover:shadow-md hover:border-primary/20 transition-all"
            >
              <div className="bg-primary/10 p-3 rounded-full">
                <FileText className="h-5 w-5 text-primary" />
              </div>
              <div>
                <div className="text-2xl font-bold">12</div>
                <div className="text-xs text-muted-foreground">Documents</div>
              </div>
            </motion.div>
            
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.4 }}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              className="glass-card p-4 rounded-xl border border-border/40 flex items-center space-x-4 hover:shadow-md hover:border-primary/20 transition-all"
            >
              <div className="bg-primary/10 p-3 rounded-full">
                <Youtube className="h-5 w-5 text-primary" />
              </div>
              <div>
                <div className="text-2xl font-bold">8</div>
                <div className="text-xs text-muted-foreground">Videos</div>
              </div>
            </motion.div>
            
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3, duration: 0.4 }}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              className="glass-card p-4 rounded-xl border border-border/40 flex items-center space-x-4 hover:shadow-md hover:border-primary/20 transition-all"
            >
              <div className="bg-primary/10 p-3 rounded-full">
                <CircleHelp className="h-5 w-5 text-primary" />
              </div>
              <div>
                <div className="text-2xl font-bold">24</div>
                <div className="text-xs text-muted-foreground">Questions</div>
              </div>
            </motion.div>
            
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.4 }}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              className="glass-card p-4 rounded-xl border border-border/40 flex items-center space-x-4 hover:shadow-md hover:border-primary/20 transition-all"
            >
              <div className="bg-primary/10 p-3 rounded-full">
                <Calendar className="h-5 w-5 text-primary" />
              </div>
              <div>
                <div className="text-2xl font-bold">5</div>
                <div className="text-xs text-muted-foreground">Days Streak</div>
              </div>
            </motion.div>
          </div>
        </motion.div>
        
        {/* Recent Summaries Section with improved cards */}
        <motion.section
          initial="hidden"
          animate="visible"
          variants={fadeInUp}
          className="mb-10"
        >
          <div className="flex justify-between items-center mb-5">
            <h2 className="text-xl font-bold flex items-center">
              <BookOpen className="mr-2 h-5 w-5 text-primary" />
              My Summaries
            </h2>
            <Button variant="outline" size="sm" asChild className="text-xs">
              <Link to="/summaries" className="flex items-center">
                View All
                <ChevronRight className="ml-1 h-3 w-3" />
              </Link>
            </Button>
          </div>
          
          <div className="grid md:grid-cols-3 gap-5">
            {recentSummaries.map((summary, index) => (
              <motion.div 
                key={index}
                initial="hidden"
                animate="visible"
                whileHover="hover"
                variants={cardVariants}
                custom={index}
                transition={{ delay: index * 0.1 }}
                className="card-wrapper"
              >
                <Card className="h-full overflow-hidden border-border/40 hover:border-primary/20">
                  <CardHeader className="p-4 pb-0">
                    <div className="flex justify-between items-start mb-2">
                      <div className="p-2 rounded-full bg-primary/10">
                        {summary.type === 'document' ? (
                          <FileText className="h-4 w-4 text-primary" />
                        ) : (
                          <Youtube className="h-4 w-4 text-primary" />
                        )}
                      </div>
                      <span className="text-xs text-muted-foreground bg-muted/50 px-2 py-1 rounded-full">{summary.date}</span>
                    </div>
                    <CardTitle className="text-lg mt-2 line-clamp-1">{summary.title}</CardTitle>
                  </CardHeader>
                  
                  <CardContent className="p-4 pt-2">
                    <p className="text-sm text-muted-foreground line-clamp-3 mb-3">{summary.summary}</p>
                    
                    <div className="mt-auto">
                      <div className="flex justify-between text-xs mb-1">
                        <span className="text-muted-foreground">Progress</span>
                        <span className="text-foreground font-medium">{summary.progress}%</span>
                      </div>
                      <div className="h-1.5 bg-muted/40 rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-gradient-to-r from-primary to-accent rounded-full" 
                          style={{ width: `${summary.progress}%` }}
                        ></div>
                      </div>
                    </div>
                  </CardContent>
                  
                  <CardFooter className="p-4 pt-2 flex justify-between items-center">
                    <div className="flex items-center text-xs text-muted-foreground">
                      <Clock className="h-3 w-3 mr-1" />
                      <span>10 min read</span>
                    </div>
                    <Button variant="ghost" size="sm" className="text-primary text-xs p-0 h-auto hover:bg-transparent hover:text-primary/80">
                      <Link to="/summaries" className="flex items-center">
                        Continue
                        <ArrowRight className="ml-1 h-3 w-3" />
                      </Link>
                    </Button>
                  </CardFooter>
                </Card>
              </motion.div>
            ))}
          </div>
        </motion.section>
        
        {/* Main tools tabs with improved styling */}
        <motion.div
          initial="hidden"
          animate="visible"
          variants={fadeInUp}
        >
          <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-8">
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-r from-primary/5 to-accent/5 rounded-xl blur-lg -z-10 opacity-50"></div>
              <TabsList className="grid grid-cols-3 max-w-2xl mx-auto bg-background/80 backdrop-blur-sm rounded-xl p-1.5 shadow-sm border border-border/30">
                <TabsTrigger value="documents" className="dashboard-tab">
                  <FileText className="h-4 w-4" />
                  <span className="hidden sm:inline ml-2">Documents</span>
                </TabsTrigger>
                <TabsTrigger value="videos" className="dashboard-tab">
                  <Youtube className="h-4 w-4" />
                  <span className="hidden sm:inline ml-2">Videos</span>
                </TabsTrigger>
                <TabsTrigger value="questions" className="dashboard-tab">
                  <CircleHelp className="h-4 w-4" />
                  <span className="hidden sm:inline ml-2">Questions</span>
                </TabsTrigger>
              </TabsList>
            </div>
            
            <TabsContent value="documents" className="space-y-6 animate-fade-in">
              <div className="grid md:grid-cols-2 gap-6">
                <Card className="border-border/40 hover:border-primary/20 transition-all shadow-sm hover:shadow-md overflow-hidden">
                  <CardHeader className="bg-gradient-to-r from-primary/5 to-accent/5 pb-3">
                    <CardTitle className="text-xl flex items-center">
                      <FileText className="mr-2 h-5 w-5 text-primary" />
                      Upload Study Material
                    </CardTitle>
                    <CardDescription>
                      Upload PDFs, documents or notes for AI analysis
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="pt-6">
                    <FileUpload onFileUpload={handleFileUpload} />
                  </CardContent>
                </Card>
                
                <Card className="border-border/40 hover:border-primary/20 transition-all shadow-sm hover:shadow-md overflow-hidden">
                  <CardHeader className="bg-gradient-to-r from-primary/5 to-accent/5 pb-3">
                    <CardTitle className="text-xl flex items-center">
                      <BookText className="mr-2 h-5 w-5 text-primary" />
                      Document Summary
                    </CardTitle>
                    <CardDescription>
                      View AI-generated insights from your document
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="pt-6">
                    <SummaryViewer summary={documentSummary} type="document" />
                  </CardContent>
                </Card>
              </div>
              
              {documentSummary && (
                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                  className="pt-6"
                >
                  <Card className="border-border/40 hover:border-primary/20 transition-all shadow-sm hover:shadow-md overflow-hidden">
                    <CardHeader className="bg-gradient-to-r from-primary/5 to-accent/5 pb-3">
                      <CardTitle className="text-xl flex items-center">
                        <Brain className="mr-2 h-5 w-5 text-primary" />
                        Generated Solutions
                      </CardTitle>
                      <CardDescription>
                        AI-generated questions and answers based on your document
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="pt-6">
                      <SolutionGenerator document={documentSummary} />
                    </CardContent>
                  </Card>
                </motion.div>
              )}
            </TabsContent>
            
            <TabsContent value="videos" className="space-y-6 animate-fade-in">
              <div className="grid md:grid-cols-2 gap-6">
                <Card className="border-border/40 hover:border-primary/20 transition-all shadow-sm hover:shadow-md overflow-hidden">
                  <CardHeader className="bg-gradient-to-r from-primary/5 to-accent/5 pb-3">
                    <CardTitle className="text-xl flex items-center">
                      <Youtube className="mr-2 h-5 w-5 text-primary" />
                      YouTube Video Processing
                    </CardTitle>
                    <CardDescription>
                      Extract key points from educational videos
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="pt-6">
                    <YouTubeSummarizer onSummarize={handleVideoSummarize} />
                  </CardContent>
                </Card>
                
                <Card className="border-border/40 hover:border-primary/20 transition-all shadow-sm hover:shadow-md overflow-hidden">
                  <CardHeader className="bg-gradient-to-r from-primary/5 to-accent/5 pb-3">
                    <CardTitle className="text-xl flex items-center">
                      <BookText className="mr-2 h-5 w-5 text-primary" />
                      Video Summary
                    </CardTitle>
                    <CardDescription>
                      View AI-generated insights from your video
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="pt-6">
                    <SummaryViewer summary={videoSummary} type="video" />
                  </CardContent>
                </Card>
              </div>
            </TabsContent>
            
            <TabsContent value="questions" className="space-y-6 animate-fade-in">
              <Card className="border-border/40 hover:border-primary/20 transition-all shadow-sm hover:shadow-md overflow-hidden">
                <CardHeader className="bg-gradient-to-r from-primary/5 to-accent/5 pb-3">
                  <CardTitle className="text-xl flex items-center">
                    <Lightbulb className="mr-2 h-5 w-5 text-primary" />
                    Question Generator
                  </CardTitle>
                  <CardDescription>
                    Generate practice questions based on your study materials
                  </CardDescription>
                </CardHeader>
                <CardContent className="pt-6">
                  <div className="mb-6">
                    <div className="flex items-center p-3 rounded-lg border border-accent/20 bg-accent/5 mb-6">
                      <AlertCircle className="h-5 w-5 text-accent mr-3" />
                      <p className="text-sm">
                        Upload a document to generate practice questions based on its content. Our AI will create targeted questions to test your understanding.
                      </p>
                    </div>
                    
                    <FileUpload 
                      onFileUpload={(file) => {
                        console.log("File uploaded for questions:", file);
                        toast({
                          title: "Document received",
                          description: "Generating questions based on your document...",
                        });
                      }} 
                    />
                  </div>
                  
                  <div className="mt-6 pt-6 border-t border-border/30">
                    <h3 className="text-lg font-medium mb-4 flex items-center">
                      <GraduationCap className="mr-2 h-4 w-4 text-primary" />
                      Suggested Topics
                    </h3>
                    
                    <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                      {["Organic Chemistry", "Neural Networks", "Quantum Physics", "Calculus", "World History", "Biology"].map((topic, index) => (
                        <Button 
                          key={index} 
                          variant="outline" 
                          className="justify-start border-border/40 hover:border-primary/20 hover:bg-primary/5"
                        >
                          <PenTool className="h-3.5 w-3.5 mr-2 text-primary" />
                          {topic}
                        </Button>
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </motion.div>
        
        {/* Study tips section */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6, duration: 0.5 }}
          className="mt-12 pt-8 border-t border-border/30"
        >
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold flex items-center">
              <Sparkles className="mr-2 h-5 w-5 text-primary" />
              Today's Study Tips
            </h2>
          </div>
          
          <div className="grid md:grid-cols-3 gap-5">
            <Card className="border-border/40 bg-gradient-to-br from-background to-muted/20 hover:shadow-md transition-all">
              <CardContent className="p-5">
                <div className="bg-primary/10 p-2 rounded-full w-fit mb-4">
                  <Clock className="h-4 w-4 text-primary" />
                </div>
                <h3 className="font-medium mb-2">Pomodoro Technique</h3>
                <p className="text-sm text-muted-foreground">Study for 25 minutes, then take a 5-minute break. Repeat 4 times, then take a longer break.</p>
              </CardContent>
            </Card>
            
            <Card className="border-border/40 bg-gradient-to-br from-background to-muted/20 hover:shadow-md transition-all">
              <CardContent className="p-5">
                <div className="bg-primary/10 p-2 rounded-full w-fit mb-4">
                  <Brain className="h-4 w-4 text-primary" />
                </div>
                <h3 className="font-medium mb-2">Active Recall</h3>
                <p className="text-sm text-muted-foreground">Test yourself on material instead of passively re-reading. Quiz yourself on key concepts.</p>
              </CardContent>
            </Card>
            
            <Card className="border-border/40 bg-gradient-to-br from-background to-muted/20 hover:shadow-md transition-all">
              <CardContent className="p-5">
                <div className="bg-primary/10 p-2 rounded-full w-fit mb-4">
                  <MessageCircle className="h-4 w-4 text-primary" />
                </div>
                <h3 className="font-medium mb-2">Teach to Learn</h3>
                <p className="text-sm text-muted-foreground">Explaining concepts to others reinforces your understanding and reveals knowledge gaps.</p>
              </CardContent>
            </Card>
          </div>
        </motion.section>
      </main>
    </div>
  );
};

export default Dashboard;
